{% set version = "2.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-startr
  version: {{ version|replace("-", "_") }}

source:
  fn: startR_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/startR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/startR/startR_{{ version }}.tar.gz
  sha256: 9ea741f68347a00dcaad648c7bff16639fe216e8831b081776eff8a8e439f6b1

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-climprojdiags
    - r-abind
    - r-bigmemory
    - r-easyncdf
    - r-future
    - r-multiapply >=2.1.1
    - r-s2dverification
  run:
    - r-base
    - r-climprojdiags
    - r-abind
    - r-bigmemory
    - r-easyncdf
    - r-future
    - r-multiapply >=2.1.1
    - r-s2dverification

test:
  commands:
    - $R -e "library('startR')"           # [not win]
    - "\"%R%\" -e \"library('startR')\""  # [win]

about:
  home: https://earth.bsc.es/gitlab/es/startR/
  license: LGPL-3.0-only
  summary: Tool to automatically fetch, transform and arrange subsets of multidimensional data sets (collections of files) stored in local and/or remote file systems or servers, using multicore capabilities where possible. The tool provides an interface to perceive a collection of data sets as a single large multidimensional
    data array, and enables the user to request for automatic retrieval, processing and arrangement of subsets of the large array. Wrapper functions to add support for custom file formats can be plugged in/out, making the tool suitable for any research field where large multidimensional data sets are involved.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
