travis:
  secure:
    BINSTAR_TOKEN: kSy976E6+y/clPrgjs47WUlk8PEbbq0roflWIW/h5AyFnXpaqW70EMQiDsUQCdOQF6UiVkpM35DqnC4MahNFwZXqFbKvNTfKgIujf5s2brWPQnsNsy6lLk1lhHTRYijYu2eWqME7KEG6aZwtcI6C3vd6AufuTi7YODbvREmkkzC73paXX9OTIbDDaFIiqP4VRN/T+uuBG6tZgUh5qF0WbCKzPrHaOpNPugx1Y+h1xq4GkAYjpZjlN4cA7jBiGfWGFI3ATNZiTc2VW2b50YfH5kavLKaTjiwwEPUop1DAOEZvNQy2v/X1oajARBvtAlTH7Y3EsuyqvSfueq2FAbffDr+zsbKMTGzjoUEKVtyIcVQMEmMLrwQL/QvgMvezAQ+REECS+6bMq9cLzZWQsgOcHtBpokovtEdQvwyxCXop4j+5eQ2KAkd0Pmh5jnFmOQMHQYPrpvhKwSimp4KOIqPIbIimSTdSD42rvqoG5ZwGDIfjKFLbQCHpc4qXOpqG1MyEqxCXef91rErfwh2VRdhnZmhe6KdbZo6yHJI4cbmtWTD11k1gi4/kLIz19cNFJTtYBBuhjjzbl9GcQT1pzRAeZ9+kCQJco/W2u+i7gVHTJ+BaNxs7+pfxkdk877pSUvS1D6USS1txvl3O3EK8XwUqsGIjNywMWfh1tuQy/JOtiDw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
